import Head from 'next/head'
import HeroSection from '../components/HeroSection'
import Venue from '../components/VenueInfo'
import ContactInfo from "../components/ContactInfo";
import ContactUs from '../components/ContactUs'

const Index = () => {
  return (
    <div>
      <Head>
        <title>Walborg Events</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='wrapper'>
        <HeroSection />
        <Venue />
      <ContactInfo />
        <ContactUs />
      </div>
    </div>
  )
}

export default Index
