import Head from "next/head";
import ContactInfo from "../components/ContactInfo";
import ContactUs from "../components/contactUs";
import Venue from "../components/VenueInfo";

const Index = () => {
  return (
    <div>
      <Head>
        <title>Walborg Events</title>
        <link
          rel='stylesheet'
          href='https://use.typekit.net/zfa2ryf.css'
        ></link>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Venue />
      <ContactInfo />
      <ContactUs />
    </div>
  );
};

export default Index;
