import Head from 'next/head'
import ContactUs from '../components/contactUs'

const Index = () => {
  return (
    <div>
      <Head>
        <title>Walborg Events</title>
        <link
          rel='stylesheet'
          href='https://use.typekit.net/zfa2ryf.css'></link>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Venue />
      <ContactUs />
    </div>
  );
};

export default Index
